version: "3.9"

services:
  server:
    build: ./backend
    container_name: server
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    networks:
      - backpackers-net
    restart: unless-stopped
  client:
    build: ./client
    container_name: client
    expose:
      - "3000"
    env_file:
      - ./client/.env
    networks:
      - backpackers-net
      - root_default
    depends_on:
      - server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"
      - "traefik.http.routers.backpackers-client.rule=Host(`suite.delhiidelight.in`)"
      - "traefik.http.routers.backpackers-client.entrypoints=websecure"
      - "traefik.http.routers.backpackers-client.tls=true"
      - "traefik.http.routers.backpackers-client.tls.certresolver=mytlschallenge"
      - "traefik.http.services.backpackers-client.loadbalancer.server.port=3000"
    
networks:
  backpackers-net:
    driver: bridge
  root_default:
    external: true

    