export const defaultInventoryItems = {
  messName: "PDDU Greater Noida",

  items: [
    { item_id: "ITM01", item_name: "Biryani Masala", current_stock: 4, unit: "box" },
    { item_id: "ITM02", item_name: "Paneer Masala", current_stock: 5, unit: "box" },
    { item_id: "ITM03", item_name: "Chilli Powder", current_stock: 3, unit: "box" },
    { item_id: "ITM04", item_name: "Chana Masala", current_stock: 3, unit: "box" },
    { item_id: "ITM05", item_name: "Meat Chicken Masala", current_stock: 2, unit: "box" },
    { item_id: "ITM06", item_name: "Pao Bhaji Masala", current_stock: 3, unit: "box" },
    { item_id: "ITM07", item_name: "Sambhar Masala", current_stock: 3, unit: "box" },
    { item_id: "ITM08", item_name: "Kitchen King", current_stock: 2, unit: "box" },
    { item_id: "ITM09", item_name: "Sabut Dhaniya", current_stock: 100, unit: "g" },
    { item_id: "ITM10", item_name: "Jeera", current_stock: 2, unit: "packet" },
    { item_id: "ITM11", item_name: "Ajinomoto", current_stock: 1, unit: "packet" },
    { item_id: "ITM12", item_name: "Khada Masala", current_stock: 100, unit: "g" },
    { item_id: "ITM13", item_name: "Tej Patta", current_stock: 50, unit: "g" },
    { item_id: "ITM14", item_name: "Paprika Powder", current_stock: 500, unit: "g" },
    { item_id: "ITM15", item_name: "Red Chilli Kutti", current_stock: 1, unit: "kg" },
    { item_id: "ITM16", item_name: "Red Chilli Powder", current_stock: 1, unit: "kg" },
    { item_id: "ITM17", item_name: "Aamchur", current_stock: 500, unit: "g" },
    { item_id: "ITM18", item_name: "Colour Box", current_stock: 10, unit: "box" },
    { item_id: "ITM19", item_name: "TATA Tea", current_stock: 24, unit: "packet" },
    { item_id: "ITM20", item_name: "Juma (Dishwasher)", current_stock: 8, unit: "pcs" },
    { item_id: "ITM21", item_name: "Ice-Cream Cup", current_stock: 2, unit: "packet" },
    { item_id: "ITM22", item_name: "Coffee Cup", current_stock: 2, unit: "packet" },
    { item_id: "ITM23", item_name: "Spoon", current_stock: 1, unit: "packet" },
    { item_id: "ITM24", item_name: "Sugar Pouch", current_stock: 120, unit: "pouch" },
    { item_id: "ITM25", item_name: "Tea Bag", current_stock: 100, unit: "pouch" },
    { item_id: "ITM26", item_name: "Boondi", current_stock: 4, unit: "packet" },
    { item_id: "ITM27", item_name: "Orange Red Powder", current_stock: 2, unit: "box" },
    { item_id: "ITM28", item_name: "Macaroni", current_stock: 2, unit: "kg" },
    { item_id: "ITM29", item_name: "Lal Masoor", current_stock: 8, unit: "kg" },
    { item_id: "ITM30", item_name: "Baking Powder", current_stock: 500, unit: "g" },
    { item_id: "ITM31", item_name: "Kala Masoor", current_stock: 4, unit: "kg" },
    { item_id: "ITM32", item_name: "Egg Tray", current_stock: 30, unit: "egg" },

    { item_id: "ITM33", item_name: "Chana Dal", current_stock: 4, unit: "kg" },
    { item_id: "ITM34", item_name: "Arhar Dal", current_stock: 12, unit: "kg" },
    { item_id: "ITM35", item_name: "Chana", current_stock: 1, unit: "kg" },
    { item_id: "ITM36", item_name: "Hari Moong", current_stock: 4, unit: "kg" },
    { item_id: "ITM37", item_name: "Kali Urad Saboot", current_stock: 12, unit: "kg" },
    { item_id: "ITM38", item_name: "Urad Dhuli", current_stock: 2, unit: "kg" },
    { item_id: "ITM39", item_name: "Rajma", current_stock: 12, unit: "kg" },
    { item_id: "ITM40", item_name: "Vinegar", current_stock: 1, unit: "bottle" },
    { item_id: "ITM41", item_name: "Magaz", current_stock: 500, unit: "g" },
    { item_id: "ITM42", item_name: "Soya Sauce", current_stock: 1, unit: "bottle" },
    { item_id: "ITM43", item_name: "Green Chilli Sauce", current_stock: 1, unit: "bottle" },
    { item_id: "ITM44", item_name: "Bhuna (Roasted) Chana", current_stock: 1.2, unit: "kg" },
    { item_id: "ITM45", item_name: "Suji", current_stock: 2, unit: "kg" },
    { item_id: "ITM46", item_name: "Imli", current_stock: 1.5, unit: "kg" },
    { item_id: "ITM47", item_name: "Jaggery", current_stock: 2.2, unit: "kg" },
    { item_id: "ITM48", item_name: "Achar", current_stock: 7, unit: "kg" },
    { item_id: "ITM49", item_name: "TATA Salt", current_stock: 13, unit: "kg" },
    { item_id: "ITM50", item_name: "Maida", current_stock: 20, unit: "kg" },
    { item_id: "ITM51", item_name: "Oil Tin", current_stock: 5, unit: "tin" },
    { item_id: "ITM52", item_name: "Dalda", current_stock: 12.5, unit: "kg" },
    { item_id: "ITM53", item_name: "Rice (Normal)", current_stock: 18, unit: "kg" },
    { item_id: "ITM54", item_name: "ATA Atta (Flour Atta)", current_stock: 61, unit: "kg" },
    { item_id: "ITM55", item_name: "Biryani Rice", current_stock: 24, unit: "kg" },
    { item_id: "ITM56", item_name: "Idli Rice", current_stock: 12, unit: "kg" },
    { item_id: "ITM57", item_name: "Nirma Soap", current_stock: 16, unit: "kg" },
    { item_id: "ITM58", item_name: "Poha", current_stock: 5, unit: "kg" },
    { item_id: "ITM59", item_name: "Besan", current_stock: 6, unit: "kg" },
    { item_id: "ITM60", item_name: "Aararot", current_stock: 19, unit: "kg" },
    { item_id: "ITM61", item_name: "Sugar", current_stock: 9, unit: "kg" },
    { item_id: "ITM62", item_name: "Peanut", current_stock: 2, unit: "kg" },
    { item_id: "ITM63", item_name: "Chole Chana", current_stock: 3, unit: "kg" },
    { item_id: "ITM64", item_name: "Garam Masala", current_stock: 5, unit: "box" },

    { item_id: "ITM65", item_name: "Yeast", current_stock: 100, unit: "g" },
    { item_id: "ITM66", item_name: "Deggi Mirch", current_stock: 3, unit: "box" },
    { item_id: "ITM67", item_name: "Kasoori Methi", current_stock: 100, unit: "g" },
    { item_id: "ITM68", item_name: "Haldi", current_stock: 500, unit: "g" },
    { item_id: "ITM69", item_name: "Black Salt", current_stock: 300, unit: "g" },
    { item_id: "ITM70", item_name: "Saboot Lal Mirch", current_stock: 350, unit: "g" },
    { item_id: "ITM71", item_name: "Jam", current_stock: 500, unit: "g" },
    { item_id: "ITM72", item_name: "Plate (Disposable)", current_stock: 200, unit: "pcs" },
    { item_id: "ITM73", item_name: "Spoon (Disposable)", current_stock: 200, unit: "pcs" },
    { item_id: "ITM74", item_name: "Cup (Disposable)", current_stock: 10, unit: "packet" },
    { item_id: "ITM75", item_name: "Tissue", current_stock: 10, unit: "packet" },
    { item_id: "ITM76", item_name: "Tomato Sauce", current_stock: 5, unit: "ltr" },
    { item_id: "ITM77", item_name: "Coffee Powder (200g Pack)", current_stock: 5, unit: "packet" },
    { item_id: "ITM78", item_name: "Coffee Powder (1kg Pack)", current_stock: 14, unit: "packet" },
    { item_id: "ITM79", item_name: "Tea Powder (1kg Pack)", current_stock: 10, unit: "packet" }
  ]
};
